version: '3.8'

services:
  db:
    image: postgres:latest
    hostname: db
    restart: always
    ports:
      - 5432:5432
    env_file: .env.development
    networks:
      - development

volumes:
  dbdata:

networks:
  development:
    driver: bridge
